### ISSUE TITLE
Issue while generating Consolidated report

### ISSUE THREAD

**Issue by Tuktuk2017** [mkolisnyk/cucumber-reports#114]
While generating consolidated report if pdf parameter is true I am getting Abstract method error as per below,

Caused by: java.lang.AbstractMethodError
	at org.apache.batik.script.InterpreterPool.<clinit>(Unknown Source)
	at org.apache.batik.bridge.BridgeContext.<clinit>(Unknown Source)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.createBridgeContext(Unknown Source)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(Unknown Source)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(Unknown Source)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.CucumberResultsCommon.convertSvgToPng(CucumberResultsCommon.java:176)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.CucumberResultsCommon.replaceSvgWithPng(CucumberResultsCommon.java:198)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.CucumberResultsCommon.exportToPDF(CucumberResultsCommon.java:213)
	at com.github.mkolisnyk.cucumber.reporting.CucumberConsolidatedReport.executeConsolidatedReport(CucumberConsolidatedReport.java:101)
	at com.github.mkolisnyk.cucumber.reporting.CucumberConsolidatedReport.execute(CucumberConsolidatedReport.java:122)
	at com.github.mkolisnyk.cucumber.reporting.CucumberConsolidatedReport.execute(CucumberConsolidatedReport.java:20)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.ConfigurableReport.execute(ConfigurableReport.java:36)
	at com.mbfs.devops.fabrics.reporting.html.HTMLReportingEngine.consolidateFABRICSReport(HTMLReportingEngine.java:169)
	at com.mbfs.devops.automation.connector.CucumberRunnerTest.tearDown(CucumberRunnerTest.java:103)
	... 23 more

**Code snippet is as follows.**
	CucumberConsolidatedReport results = new CucumberConsolidatedReport();
				results.setOutputDirectory("C:\\Users\\samukhe\\workspace\\ECM\\target");
				results.setOutputName("cucumber-results");
				results.setPdfPageSize("A4 landscape");
				results.setSourceFile("C:\\Users\\samukhe\\workspace\\ECM\\target\\cucumber.json");
			

				try {
					results.execute(
						new File("C:\\Users\\samukhe\\workspace\\ECM\\config\\consolidated_batch.json"),
						true
						
						
					);
				//	results.exportToPDF(new File("C:\\Users\\samukhe\\workspace\\ECM\\target\\cucumber-results-batch-config1.html"),"Consolidated PDF");
				//	results.
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				System.out.println("Consolidated Report Completed");

**Comment by Tuktuk2017** [comment]
Any update on below.
