### ISSUE TITLE
Cucumber Report is not generating

### ISSUE THREAD

**Issue by ankitonedirect** [mkolisnyk/cucumber-reports#171]
Hello,

I am using java + maven project with cucumber report . When I try to run my application code getting below error.

java.lang.AssertionError: Results Overview Report: Configuration file specified doesn't exist. For more information, please, refer to: http://mkolisnyk.github.io/cucumber-reports/overview-report
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.KECompatibleReport.execute(KECompatibleReport.java:29)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.runOverviewReport(ReportRunner.java:51)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.run(ReportRunner.java:296)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.run(ExtendedCucumber.java:161)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Can you please help me out in this issue.

**Comment by ankitonedirect** [comment]
Its been resolved after adding config file .thank you for your contribution.
