### ISSUE TITLE
ExtendedParallelCucumber.class 1.3.4 is not working 

### ISSUE THREAD

**Issue by SalimAnsari1808** [mkolisnyk/cucumber-reports#195]
Hello,
Previously am using ExtendedCucumber.class with below set of file for report generation and it is working fine for me 
cucumber-runner-1.0.8
Java Version-8
Cucumber Version-1.2.5
JUnit Version-4.12
Now for parallel execution, when i updated my cucumber-runner-1.3.4 (keeping all other versions same) then am getting below error messages and no reports are getting generated .Also ExtendedCucumber.class also not generating reports with cucumber-runner-1.3.4

Runner File:
@RunWith(ExtendedParallelCucumber.class)
@ExtendedCucumberOptions(
	jsonReport = "target/cucumber-report.json",
	jsonUsageReport = "target/cucumber-usage.json",
	outputFolder  = "target/DATE(dd-MM-yyyy)", 
	usageReport = true,
	detailedReport = true, 
	detailedAggregatedReport = true,
	toPDF = true,
        retryCount = 1,
        threadsCount = 2 )
@CucumberOptions(
		features = "src/test/resources/functionalTests"
		,glue={"classpath:stepDefinations"}
		,format = {	"pretty:target/cucumber-pretty.txt", 
					"html:target/cucumber-html-report", 
					"json:target/cucumber-report.json", 
					"usage:target/cucumber-usage.json",
					"junit:target/cucumber.xml"}
		,tags = {"@Smoke1"}
		,dryRun = false
		)
public class TestRunner {
}
Error Messages(Am running two threads:
First Error Message:
java.lang.AssertionError: Usage Report: The source file specified doesn't exist. For more information, please, refer to: http://mkolisnyk.github.io/cucumber-reports/usage-report. Was looking for path: "C:\Users\WS-S00-140\eclipse-workspace\decisionSourceCucumberFramework\target\5\cucumber-usage.json"
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.github.mkolisnyk.cucumber.reporting.CucumberUsageReporting.validateParameters(CucumberUsageReporting.java:389)
	at com.github.mkolisnyk.cucumber.reporting.CucumberUsageReporting.execute(CucumberUsageReporting.java:401)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.runUsageReport(ReportRunner.java:32)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.run(ReportRunner.java:295)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.run(ExtendedCucumber.java:161)
	at com.github.mkolisnyk.cucumber.runner.parallel.CucumberRunnerThread.run(CucumberRunnerThread.java:25)
	at java.base/java.lang.Thread.run(Thread.java:844)
java.io.FileNotFoundException
	at com.github.mkolisnyk.cucumber.reporting.interfaces.CucumberResultsCommon.readFileContent(CucumberResultsCommon.java:162)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:39)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:51)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:45)
	at com.github.mkolisnyk.cucumber.reporting.CucumberDetailedResults.execute(CucumberDetailedResults.java:171)
	at com.github.mkolisnyk.cucumber.reporting.CucumberDetailedResults.execute(CucumberDetailedResults.java:132)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.runDetailedReport(ReportRunner.java:108)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.run(ReportRunner.java:299)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.run(ExtendedCucumber.java:161)
	at com.github.mkolisnyk.cucumber.runner.parallel.CucumberRunnerThread.run(CucumberRunnerThread.java:25)
	at java.base/java.lang.Thread.run(Thread.java:844)
java.io.FileNotFoundException
	at com.github.mkolisnyk.cucumber.reporting.interfaces.CucumberResultsCommon.readFileContent(CucumberResultsCommon.java:162)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:39)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:51)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:45)
	at com.github.mkolisnyk.cucumber.reporting.CucumberDetailedResults.execute(CucumberDetailedResults.java:171)
	at com.github.mkolisnyk.cucumber.reporting.CucumberDetailedResults.execute(CucumberDetailedResults.java:132)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.runDetailedAggregatedReport(ReportRunner.java:133)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.run(ReportRunner.java:300)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.run(ExtendedCucumber.java:161)
	at com.github.mkolisnyk.cucumber.runner.parallel.CucumberRunnerThread.run(CucumberRunnerThread.java:25)
	at java.base/java.lang.Thread.run(Thread.java:844)

Second Error Message:
java.lang.AssertionError: Usage Report: The source file specified doesn't exist. For more information, please, refer to: http://mkolisnyk.github.io/cucumber-reports/usage-report. Was looking for path: "C:\Users\WS-S00-140\eclipse-workspace\decisionSourceCucumberFramework\target\3\cucumber-usage.json"
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.github.mkolisnyk.cucumber.reporting.CucumberUsageReporting.validateParameters(CucumberUsageReporting.java:389)
	at com.github.mkolisnyk.cucumber.reporting.CucumberUsageReporting.execute(CucumberUsageReporting.java:401)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.runUsageReport(ReportRunner.java:32)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.run(ReportRunner.java:295)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.run(ExtendedCucumber.java:161)
	at com.github.mkolisnyk.cucumber.runner.parallel.CucumberRunnerThread.run(CucumberRunnerThread.java:25)
	at java.base/java.lang.Thread.run(Thread.java:844)
java.io.FileNotFoundException
	at com.github.mkolisnyk.cucumber.reporting.interfaces.CucumberResultsCommon.readFileContent(CucumberResultsCommon.java:162)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:39)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:51)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:45)
	at com.github.mkolisnyk.cucumber.reporting.CucumberDetailedResults.execute(CucumberDetailedResults.java:171)
	at com.github.mkolisnyk.cucumber.reporting.CucumberDetailedResults.execute(CucumberDetailedResults.java:132)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.runDetailedReport(ReportRunner.java:108)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.run(ReportRunner.java:299)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.run(ExtendedCucumber.java:161)
	at com.github.mkolisnyk.cucumber.runner.parallel.CucumberRunnerThread.run(CucumberRunnerThread.java:25)
	at java.base/java.lang.Thread.run(Thread.java:844)
java.io.FileNotFoundException
	at com.github.mkolisnyk.cucumber.reporting.interfaces.CucumberResultsCommon.readFileContent(CucumberResultsCommon.java:162)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:39)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:51)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:45)
	at com.github.mkolisnyk.cucumber.reporting.CucumberDetailedResults.execute(CucumberDetailedResults.java:171)
	at com.github.mkolisnyk.cucumber.reporting.CucumberDetailedResults.execute(CucumberDetailedResults.java:132)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.runDetailedAggregatedReport(ReportRunner.java:133)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.run(ReportRunner.java:300)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.run(ExtendedCucumber.java:161)
	at com.github.mkolisnyk.cucumber.runner.parallel.CucumberRunnerThread.run(CucumberRunnerThread.java:25)
	at java.base/java.lang.Thread.run(Thread.java:844)
java.lang.AssertionError: Usage Report: The source file isn't defined. For more information, please, refer to: http://mkolisnyk.github.io/cucumber-reports/usage-report
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at com.github.mkolisnyk.cucumber.reporting.CucumberUsageReporting.validateParameters(CucumberUsageReporting.java:379)
	at com.github.mkolisnyk.cucumber.reporting.CucumberUsageReporting.execute(CucumberUsageReporting.java:401)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.runUsageReport(ReportRunner.java:32)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.run(ReportRunner.java:295)
	at com.github.mkolisnyk.cucumber.runner.ExtendedParallelCucumber.runReports(ExtendedParallelCucumber.java:279)
	at com.github.mkolisnyk.cucumber.runner.ExtendedParallelCucumber.run(ExtendedParallelCucumber.java:323)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
java.lang.NullPointerException
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:50)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:45)
	at com.github.mkolisnyk.cucumber.reporting.CucumberDetailedResults.execute(CucumberDetailedResults.java:171)
	at com.github.mkolisnyk.cucumber.reporting.CucumberDetailedResults.execute(CucumberDetailedResults.java:132)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.runDetailedReport(ReportRunner.java:108)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.run(ReportRunner.java:299)
	at com.github.mkolisnyk.cucumber.runner.ExtendedParallelCucumber.runReports(ExtendedParallelCucumber.java:279)
	at com.github.mkolisnyk.cucumber.runner.ExtendedParallelCucumber.run(ExtendedParallelCucumber.java:323)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
java.lang.NullPointerException
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:50)
	at com.github.mkolisnyk.cucumber.reporting.interfaces.AggregatedReport.readFileContent(AggregatedReport.java:45)
	at com.github.mkolisnyk.cucumber.reporting.CucumberDetailedResults.execute(CucumberDetailedResults.java:171)
	at com.github.mkolisnyk.cucumber.reporting.CucumberDetailedResults.execute(CucumberDetailedResults.java:132)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.runDetailedAggregatedReport(ReportRunner.java:133)
	at com.github.mkolisnyk.cucumber.runner.ReportRunner.run(ReportRunner.java:300)
	at com.github.mkolisnyk.cucumber.runner.ExtendedParallelCucumber.runReports(ExtendedParallelCucumber.java:279)
	at com.github.mkolisnyk.cucumber.runner.ExtendedParallelCucumber.run(ExtendedParallelCucumber.java:323)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

POM.File:
<dependencies>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.5</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-jvm</artifactId>
			<version>1.2.5</version>
			<type>pom</type>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.5</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-jvm-deps</artifactId>
			<version>1.0.5</version>
		</dependency>

		<dependency>
			<groupId>net.masterthought</groupId>
			<artifactId>cucumber-reporting</artifactId>
			<version>1.0.0</version>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>gherkin</artifactId>
			<version>2.12.2</version>
		</dependency>

		
		<dependency>
		    <groupId>junit</groupId>
		    <artifactId>junit</artifactId>
		    <version>4.12</version>
		    <scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.5.3</version>
		</dependency>
		
		
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-picocontainer</artifactId>
			<version>1.2.5</version>
			<scope>test</scope>
		</dependency>
		
		
		<dependency>
		    <groupId>com.vimalselvam</groupId>
		    <artifactId>cucumber-extentsreport</artifactId>
		    <version>3.0.2</version>
		</dependency>
		
		
		<dependency>
		    <groupId>com.aventstack</groupId>
		    <artifactId>extentreports</artifactId>
		    <version>3.1.5</version>
		</dependency>
		
		<dependency>
		    <groupId>com.github.mkolisnyk</groupId>
		    <artifactId>cucumber-runner</artifactId>
		    <version>1.3.4</version> 
		</dependency>
		 
		
		<dependency>
		    <groupId>com.github.mkolisnyk</groupId>
		    <artifactId>cucumber-reports</artifactId>
		    <version>1.3.5</version>
		    <type>pom</type>
		</dependency>
		
		
		<dependency>
		    <groupId>org.apache.poi</groupId>
		    <artifactId>poi-ooxml</artifactId>
		    <version>3.9</version>
		</dependency>

  </dependencies>
  
    <build>
	    <plugins>
		      <plugin>
		        <groupId>org.apache.maven.plugins</groupId>
		        <artifactId>maven-compiler-plugin</artifactId>
		        <version>3.7.0</version>
		        <configuration>
		          <source>1.8</source>
		          <target>1.8</target>
		           <encoding>UTF-8</encoding>          
		        </configuration>
		      </plugin>	
      	</plugins>
  	</build>

Thanks

**Comment by SalimAnsari1808** [comment]
This issue is resolved and now reports are getting generated by taking reference of below issues #
1. Error while running parallel #126
2. jsonUsageReports parameter is not including the other usage JSON files into the report #174 

Thanks and thumb up for your good work. It is really very nice reporting. am also trying running scenarios in parallel. Get back to you in case any clarification required.
