### ISSUE TITLE
Getting the issue - java.lang.AssertionError: Results Overview Report: The source file specified doesn't exist

### ISSUE THREAD

**Issue by samalonilumira** [mkolisnyk/cucumber-reports#201]
I am getting all my reports with scenario heading displaying 'null' .. The reports do not display the actual cucumber scenario heading / test case. Please help me on this. 

**************************************ERROR STACKTRACE ************************
Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err: java.lang.AssertionError: Results Overview Report: The source file specified doesn't exist. For more information, please, refer to: http://mkolisnyk.github.io/cucumber-reports/overview-report. Was looking for path: "/Users/sampada/Lumira/repos/lumira-automation/lumira-automation-rest/target2/cucumber.json"

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at org.junit.Assert.fail(Assert.java:88)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at org.junit.Assert.assertTrue(Assert.java:41)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at com.github.mkolisnyk.cucumber.reporting.CucumberResultsOverview.validateParameters(CucumberResultsOverview.java:196)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at com.github.mkolisnyk.cucumber.reporting.CucumberResultsOverview.executeOverviewReport(CucumberResultsOverview.java:154)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at com.github.mkolisnyk.cucumber.reporting.CucumberResultsOverview.executeOverviewReport(CucumberResultsOverview.java:151)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at com.github.mkolisnyk.cucumber.reporting.CucumberResultsOverview.execute(CucumberResultsOverview.java:208)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at com.github.mkolisnyk.cucumber.runner.ReportRunner.runOverviewReport(ReportRunner.java:46)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at com.github.mkolisnyk.cucumber.runner.ReportRunner.run(ReportRunner.java:174)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.run(ExtendedCucumber.java:160)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at java.lang.reflect.Method.invoke(Method.java:498)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)

Test: Test class com.lumiradx.qa.rest.runners.ExtendedCucumberTests produced standard out/err:  at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)

**Comment by pranjal815** [comment]
I am facing the same issue.. can anyone guide us on this please?

**Comment by pranjal815** [comment]
@samalonilumira  I was facing the same issue but using below configuration in runner class, I was able to remove the error:

@RunWith(ExtendedCucumber.class)
@ExtendedCucumberOptions(jsonReport = "target/cucumber.json",
        overviewReport = true,
        outputFolder = "target")
@CucumberOptions(plugin = { "html:target/cucumber-html-report",
        "json:target/cucumber.json", "pretty:target/cucumber-pretty.txt",
        "usage:target/cucumber-usage.json", "junit:target/cucumber-results.xml" },
        features = { "./src/test/java/com/github/mkolisnyk/cucumber/features" },
        glue = { "com/github/mkolisnyk/cucumber/steps" })
public class SampleCucumberTest {
}

**Comment by samalonilumira** [comment]
@pranjal815 thanks for this. i'll try this out!
