### ISSUE TITLE
Error running Junit test with ExtendedCucumberOptions with latest io.cucumber dependencies

### ISSUE THREAD

**Issue by CucumberUserR** [mkolisnyk/cucumber-reports#203]
Hello,

Can you please help resolving the error below, observing this error with latest  io.cucumber dependencies

Exception Details:
  Location:
    cucumber/runtime/ExtendedRuntime.runStep(Ljava/lang/String;Lgherkin/formatter/model/Step;Lgherkin/formatter/Reporter;Lgherkin/I18n;)V @94: invokeinterface
  Reason:
    Type 'cucumber/runtime/StepDefinitionMatch' (current frame, stack[1]) is not assignable to 'gherkin/formatter/model/Match'
  Current Frame:

at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.createRuntime(ExtendedCucumber.java:93)
	at com.github.mkolisnyk.cucumber.runner.ExtendedCucumber.<init>(ExtendedCucumber.java:52)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)

**Comment by CucumberUserR** [comment]
Any updates on this issue, thank you

**Comment by trzewa** [comment]
Hello,
I join to request, I have the same issue,
thank you in advance.

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    cucumber/runtime/ExtendedRuntime.runStep(Ljava/lang/String;Lgherkin/formatter/model/Step;Lgherkin/formatter/Reporter;Lgherkin/I18n;)V @94: invokeinterface
  Reason:
    Type 'cucumber/runtime/StepDefinitionMatch' (current frame, stack[1]) is not assignable to 'gherkin/formatter/model/Match'
  Current Frame:
    bci: @94
    flags: { }
    locals: { 'cucumber/runtime/ExtendedRuntime', 'java/lang/String', 'gherkin/formatter/model/Step', 'gherkin/formatter/Reporter', 'gherkin/I18n', 'cucumber/runtime/StepDefinitionMatch' }
    stack: { 'gherkin/formatter/Reporter', 'cucumber/runtime/StepDefinitionMatch' }

**Comment by Reddy447** [comment]
I am also getting same issue with io.cucumber. So used info.cukes group me.
